name: commitLogOnPush 
on: push

jobs: 
  populate: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
           ref: ${{ github.event.pull_request.head.sah }}
           fetch-depth: 0
    - run: git log --pretty="%H, %cI, %an, %s" > data/octokit.csv
    - run: git config --local user.email "action@github.com"
    - run: git config --local user.name "GitHub Action"
    - run: git add data
    - run: git commit -m "data/octokit.csv updated"
    - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

          
      
          
