name: commitLogOnPush 
on: push

jobs: 
  populate: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
           #This Allows git log to acess full history instead of just latest
            ref: ${{ github.event.pull_request.head.sah }}
            fetch-depth: 0
      #Curently Runs Once Through Each File and Fetches Filename, Commit_ID, Time/Date of Commit, Author of File, Author of Commit and Subject
    - run: git ls-files | while read file; git log -n 1 --pretty=" $file , %H , %ci , %an , %cn , %s " -- $file; done > data/octokit.csv
      #Sets Up and Executees Auto Commit + Push
    - run: git config --local user.email "action@github.com"
    - run: git config --local user.name "GitHub Action"
    - run: git add data
    - run: git commit -m "data/octokit.csv updated"
    - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
      env:
         #Ensure Read Package Token is Created Before Using
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
          
     
    
          

          
      
          
          
          
     
    
          

          
      
          
          
     
    
          

          
      
          
          
          
     
    
          

          
      
          
