name: commitLogOnPush 
on: push

jobs: 
  populate: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
           ref: ${{ github.event.pull_request.head.sah }}
           fetch-depth: 0
    - uses: gr2m/write-csv-file-action@v1.x
      with:
          path: data/octokit.csv
          columns: open issues,closed issues,open pull requests,closed pull requests
          "open issues": "Commit_ID"
          "closed issues": "Date/Time"
          "open pull requests": "Author"
          "closed pull requests": "Subject"
    - run: git log --pretty="%H, %cI, %an, %s" > data/octokit.csv
    - run: git config --local user.email "action@github.com"
    - run: git config --local user.name "GitHub Action"
    - run: git add data
    - run: git commit -m "data/octokit.csv updated"
    - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  headers:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout Repo
          uses: actions/checkout@master
        - name: Read CSV
          id: csv
          uses: juliangruber/read-file-action@v1
          with:
            path: data/octokit.csv
        - uses: petems/csv-to-md-table-action@master
          id: csv-table-output
          with:
            csvinput: |
                  Commit_ID Date Time Author Subject
                  ${{ steps.csv.outputs.content }}
        - uses: mshick/add-pr-comment@v1
          with:
            message: |
              ${{steps.csv-table-output.outputs.markdown-table}}
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
            allow-repeats: true
        - run: git config --local user.email "action@github.com"
        - run: git config --local user.name "GitHub Action"
        - run: git add data
        - run: git commit -m "data/octokit.csv updated"
        - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
          

          
      
          
