name: commitLogOnPush 
on: push

jobs:
  testing: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git log --pretty=format:%cI,%h,%an,%ae,%s > data/octokit.csv
    - run: git config --local user.email "action@github.com"
    - run: git config --local user.name "GitHub Action"
    - run: git add data
    - run: git commit -m "data/octokit.csv updated"
    - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
    
