name: commitLogOnPush 
on: push

jobs:
  headers: 
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      # append stats to data/octokit.csv
      - uses: gr2m/write-csv-file-action@v1.x
        with:
          path: data/octokit.csv
          columns: open issues,closed issues,open pull requests,closed pull requests
          "open issues": 1
          "closed issues": 2
          "open pull requests": 3
          "closed pull requests": 4
      # push updated file back to main branch
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: git add data
      - run: git commit -m "data/octokit.csv updated"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  populate: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
           ref: ${{ github.event.pull_request.head.sah }}
           fetch-depth: 0
    - run: git log --pretty="%n$file,%H, %cI, %an, %s" > data/octokit.csv
    - run: git config --local user.email "action@github.com"
    - run: git config --local user.name "GitHub Action"
    - run: git add data
    - run: git commit -m "data/octokit.csv updated"
    - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
 


 
          
      
          
