name: Updating Requirements from CSV

on:
  push:
    paths:
      - 'Requirements.csv'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: BSFishy/pip-action@v1
      with:
         packages: |
          pandas
          openpyxl
    - run: python data/csv2xlsx.py
    - name: Sync Before Commit
      uses: repo-sync/pull-request@v2
      with:
            destination_branch: "main"
            github_token: ${{ secrets.GITHUB_TOKEN }}  
    - run: git config --local user.email "action@github.com"
    - run: git config --local user.name "GitHub Action"
    - run: git add Requirements.xlsx
    - run: git commit -m "Requirements updated"
    - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
      env:
         #Ensure Read Package Token is Created Before Using
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

